# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-06 07:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0009_auto_20170606_1302'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='categories',
            field=models.TextField(default=''),
        ),
    ]
