# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-06 08:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0010_post_categories'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(default='static/img/default.jpg', upload_to='photo'),
        ),
    ]
