# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-21 12:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0014_auto_20180320_2101'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='assos_post',
        ),
        migrations.AddField(
            model_name='category',
            name='assos_post',
            field=models.ManyToManyField(to='posts.Post'),
        ),
    ]
